# Generated by Django 2.0.4 on 2018-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_exhibit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='hasExit',
            field=models.BooleanField(default=True),
        ),
    ]
