# Generated by Django 2.0.4 on 2018-04-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_exhibit_hasexit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(help_text='Enter Direction To Travel', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='hasExit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='neighbors',
            name='fromExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromExhibit', to='zoo.Exhibit'),
        ),
        migrations.AddField(
            model_name='neighbors',
            name='toExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toExhibit', to='zoo.Exhibit'),
        ),
    ]
